#!/bin/bash
set -e

echo "Deployment started ..."

# Traer Ãºltimos cambios
echo "ðŸ“¥ Pulling latest changes..."
git pull origin main  

# Installing Dependencies
echo "Installing Dependencies..."
npm install --yes

# Creating a build 
echo "Building application"
npm run build

# Copying dist to /var/www/Deploy-Test
echo "Copying dist to /var/www/Deploy-Test"
sudo cp -r dist/* /var/www/Deploy-Test

echo "Deployment Finished!"
